### ISSUE TITLE
ES6 Sources

### ISSUE THREAD

**Issue by dmackerman** [gabel/karma-webpack-example#2]
How would you update this to use ES6 sources? The coverage stuff works (thanks), but all of my coverage reports are on the transpiled sources. 

Any advice you could give would be amazing!

**Comment by 1001b** [comment]
Use a loader and add to your repo, karma-babel-preprocessor...in your karma config file, it is better you leave out plugins property entirely so karma can look for the modules itself...

webpack: {
      module: {
        loaders: [
          {test: /.jsx?$/, exclude: /node_modules/, loader: 'babel-loader'}
        ]
      },
      resolve: {
        extensions: ['', '.js', '.jsx']
      }
    }

**Comment by gabel** [comment]
@1001b thanks for the example... i'm going to test it.

**Comment by SimeonC** [comment]
@dmackerman Looks like the trick was found here: http://stackoverflow.com/questions/32170176/getting-karma-code-coverage-for-pre-transpilation-souce-code simply swap:

```
postLoaders: [{
    test: /\.js/,
    exclude: /(test|node_modules|bower_components)/,
    loader: 'istanbul-instrumenter'
}]
```

For:

```
preLoaders: [{
    test: /\.js(x|)$/,
    exclude: /(node_modules|__tests__)/,
    loader: 'isparta'
}]
```
