### ISSUE TITLE
Webpack?!

### ISSUE THREAD

**Issue by ViggoV** [gabel/karma-webpack-example#5]
I don't see webpack anywhere in the project except for the package.json file. Are you not using it at all or am I missing some secret way of doing webpack? I ask because it is the second time I hit upon a github project that is supposed to be an example of js testing with webpack that doesn't have a shred of webpack related code in it..

**Comment by gabel** [comment]
@ViggoV Webpack is used to bundle the code that is run through karma test runner on the fly. That's what this repository is about. A **karma** **webpack** **example**. 😉 

https://github.com/gabel/karma-webpack-example/blob/e3422200bca06f6e7521e80fc091a5beb43b47d1/karma.conf.js#L1

https://github.com/gabel/karma-webpack-example/blob/e3422200bca06f6e7521e80fc091a5beb43b47d1/karma.conf.js#L33-L55

**Comment by ViggoV** [comment]
Ah. I realized that was the Karma way after I wrote this, but it seems pretty backwards to me to have the webpack config folded into ones testrunner! I am just trying (well, I was trying) to do some basic testing in my existing webpack setups..

**Comment by gabel** [comment]
In a bigger setup you would split this for sure. This example was created 3 years ago when webpack came up.
